"""Build a signed `.visq` deployment package from trained model checkpoints.

This script provides the operational entry point for packaging a trained
VisQ.AI model for deployment. Packaging is intentionally kept separate from
model training and evaluation workflows so that creating a client-deliverable
artifact does not depend on the retraining or evaluation entry point.

The output directory is generated automatically using a dated run directory,
and the package name is generated by :class:`SecurePredictorPackager`. This
ensures that each invocation produces a fresh package without requiring the
operator to select or remember an output path or package name.

The script can package explicitly supplied checkpoints or automatically locate
the latest available checkpoint set. It also supports configuring deployment
metadata, ensemble packaging, package signing, and optional preservation of
the generated private signing key.

The module is located under `scripts/` rather than `src/visqai/` because
it is an operational script rather than part of the installable library. It
is not registered as a console-script entry point and is intended to be run
from the repository root, for example::

    python scripts/package.py

The default `--source-dir` value is interpreted relative to the current
working directory rather than relative to this script's location.

This module replaces the earlier hardcoded packaging entry point from
`scripts/packager.py` and the former `cli/package_model.py` implementation.

Functions:
    parse_args: Parse command-line arguments for the packaging workflow.
    main: Create and execute a deployment packaging run.
"""

from __future__ import annotations

import argparse

from visqai import constants, paths
from visqai.logging_config import configure_logging
from visqai.packaging.packager import SecurePredictorPackager, get_latest_checkpoints


def parse_args(argv=None):
    """Parse command-line arguments for the model packaging workflow.

    Args:
        argv: Optional sequence of command-line arguments to parse. If
            `None`, arguments are read from `sys.argv`. Supplying a
            sequence is useful when invoking the parser programmatically or
            from tests.

    Returns:
        argparse.Namespace: Parsed packaging options, including checkpoint
        locations, source directory, deployment metadata, signing options,
        ensemble configuration, and private-key output settings.
    """
    p = argparse.ArgumentParser(
        description="Package a trained visqai model into a signed deployment zip."
    )
    p.add_argument(
        "--checkpoints-dir",
        dest="experiments_dir",
        default=constants.CHECKPOINTS_DIR,
        help="Used to auto-locate the latest checkpoint(s) if --checkpoints isn't given.",
    )
    p.add_argument(
        "--checkpoints",
        nargs="+",
        default=None,
        help="Explicit checkpoint path(s). Overrides --checkpoints-dir auto-detection.",
    )
    p.add_argument("--source-dir", default="src/visqai")
    p.add_argument("--version", default="1.0")
    p.add_argument("--author", default="Unknown")
    p.add_argument("--client", default="Unknown")
    p.add_argument("--notes", default="")
    p.add_argument("--model-created-date", default=None)
    p.add_argument(
        "--ensemble",
        action="store_true",
        default=None,
        help="Force ensemble packaging. Auto-detected from checkpoint count if omitted.",
    )
    p.add_argument("--no-signing", dest="enable_signing", action="store_false", default=True)
    p.add_argument(
        "--save-private-key", default=None, help="Path to also save the generated private key to."
    )
    return p.parse_args(argv)


def main(argv=None):
    """Build and sign a deployment package from trained model checkpoints.

    The output directory is created as a fresh dated run directory beneath
    the configured production directory. Checkpoints are taken from the
    explicitly supplied `--checkpoints` arguments when present; otherwise,
    the latest available checkpoints are located automatically using
    `--checkpoints-dir`.

    Logging is configured for the generated output directory before the
    packaging operation begins. The selected checkpoints and deployment
    metadata are then passed to :class:`SecurePredictorPackager`, which
    creates the deployment package and optionally signs it.

    Args:
        argv: Optional sequence of command-line arguments. If `None`,
            arguments are read from `sys.argv`.

    Raises:
        Any exception raised while locating checkpoints, configuring the
            packager, or creating the deployment package is propagated to the
            caller.
    """
    args = parse_args(argv)
    output_dir = paths.dated_run_dir(constants.PRODUCTION_DIR)
    configure_logging(log_dir=output_dir)

    if args.checkpoints:
        checkpoints = args.checkpoints
    else:
        print("Locating latest checkpoints...")
        checkpoints = get_latest_checkpoints(args.experiments_dir)

    packager = SecurePredictorPackager(
        output_dir=output_dir,
        source_dir=args.source_dir,
        enable_signing=args.enable_signing,
    )
    packager.package(
        model_paths=checkpoints,
        model_created_date=args.model_created_date,
        client=args.client,
        author=args.author,
        version=args.version,
        notes=args.notes,
        is_ensemble=args.ensemble,
        save_private_key=args.save_private_key,
    )


if __name__ == "__main__":
    main()
